name: Предложение по улучшению процесса
description: Предложите изменение в процессах, документации или правилах организации NotDoneByOne
title: "[ПРОЦЕСС]: "
labels: ["type: улучшение"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Предложение по улучшению процессов NotDoneByOne
        
        Заполните эту форму, чтобы предложить изменения в процессах, документации или правилах организации.
        
        Перед заполнением убедитесь, что:
        - Прочитали соответствующие документы организации
        - Проверили, нет ли уже похожих предложений
        - Обсудили идею с командой (если это возможно)

  - type: textarea
    id: description
    attributes:
      label: Описание предложения
      description: Кратко и четко опишите предлагаемое изменение
      placeholder: "Например: Предлагаю изменить процесс код-ревью..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Проблема, которую решает предложение
      description: Опишите проблему или неэффективность текущего процесса
      placeholder: |
        - Текущий процесс код-ревью занимает слишком много времени...
        - В документации не хватает раздела о...
        - Нет четкого процесса для...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
      description: Подробно опишите, как вы предлагаете изменить процесс или документацию
      placeholder: "Пошагово опишите ваше предложение..."
    validations:
      required: true

  - type: checkboxes
    id: documents_to_change
    attributes:
      label: Какие документы или процессы нужно изменить?
      description: Отметьте все подходящие варианты
      options:
        - label: Onboarding Guide
        - label: Руководство по вкладу (CONTRIBUTING.md)
        - label: Кодекс поведения (CODE_OF_CONDUCT.md)
        - label: Шаблоны репозиториев
        - label: Шаблоны Issues/PR
        - label: Систему меток
        - label: GitHub Actions/Workflows
        - label: Другие процессы (опишите ниже)

  - type: textarea
    id: other_changes
    attributes:
      label: Другие процессы для изменения
      description: Если вы отметили "Другие процессы" выше, укажите какие именно
      placeholder: "Например: процесс онбординга новых участников, система отчетности..."
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Ожидаемые преимущества
      description: Какие улучшения принесет ваше предложение?
      placeholder: |
        - Ускорение процесса разработки
        - Улучшение понимания новых участников
        - Снижение количества ошибок
        - Повышение качества кода
      value: |
        - 
        - 
        - 
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Потенциальные риски и как их минимизировать
      description: Опишите возможные негативные последствия и способы их избежать
      placeholder: |
        - Риск: Может замедлить процесс разработки
          Решение: Внедрять постепенно с метриками
        - Риск: Требует обучения команды
          Решение: Провести воркшоп и обновить документацию
    validations:
      required: false

  - type: dropdown
    id: impact_level
    attributes:
      label: Уровень влияния предложения
      description: Насколько сильно предложение повлияет на работу организации
      options:
        - Незначительное (косметические изменения)
        - Среднее (изменение отдельных процессов)
        - Высокое (изменение ключевых процессов)
        - Критическое (перестройка всей системы)
    validations:
      required: true

  - type: dropdown
    id: affected_users
    attributes:
      label: Кто будет затронут изменениями?
      description: Кто должен будет адаптироваться к новым процессам
      multiple: true
      options:
        - Все внутренние разработчики
        - Только новые участники
        - Только опытные участники
        - Внешние контрибьюторы
        - Модераторы и ревьюверы
        - Основатели организации
    validations:
      required: true

  - type: checkboxes
    id: related_docs
    attributes:
      label: Связанные документы
      description: Какие документы организации относятся к этому предложению?
      options:
        - label: "[Onboarding Guide](ONBOARDING.md)"
        - label: "[Руководство по вкладу](CONTRIBUTING.md)"
        - label: "[Кодекс поведения](CODE_OF_CONDUCT.md)"
        - label: "[Шаблоны репозиториев](repository-templates/)"

  - type: checkboxes
    id: priority
    attributes:
      label: Приоритет предложения
      description: Насколько срочно нужно рассмотреть это предложение?
      options:
        - label: priority: высокий (блокирует работу или критически важно)
        - label: priority: средний (важно, но может подождать)
        - label: priority: низкий (косметическое улучшение)

  - type: checkboxes
    id: community_help
    attributes:
      label: Требуется обсуждение сообщества
      description: Нужно ли обсуждение с более широким кругом участников?
      options:
        - label: "Да, требуется обсуждение сообщества (добавить метку 'нужна помощь')"

  - type: textarea
    id: additional_info
    attributes:
      label: Дополнительная информация
      description: Любая другая информация, которая поможет оценить предложение
      placeholder: |
        - Ссылки на аналогичные процессы в других организациях
        - Примеры реализации
        - Исследования или данные, подтверждающие необходимость изменений
        - Предложения по внедрению (поэтапный план, сроки)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Что будет дальше?
        
        1. Ваше предложение будет рассмотрено командой в течение **7 рабочих дней**
        2. Может потребоваться дополнительная информация или обсуждение
        3. Если предложение будет принято, будет создан план реализации
        4. Вы будете получать обновления в этом Issue
        
        Спасибо за ваш вклад в улучшение NotDoneByOne!