name: Вопрос по процессам организации
description: Задайте вопрос о процессах, правилах или документации NotDoneByOne
title: "[ВОПРОС]: "
labels: ["type: вопрос"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Вопросы по процессам NotDoneByOne
        
        Задавайте здесь вопросы о:
        - Процессах разработки и взаимодействия
        - Правилах и политиках организации
        - Документации и руководствах
        - Любых аспектах работы NDO
        
        Перед заданием вопроса, пожалуйста, проверьте:
        1. Соответствующую документацию
        2. Существующие Issues (чтобы не дублировать вопросы)
        3. Чат организации (для быстрых вопросов)

  - type: textarea
    id: question
    attributes:
      label: Ваш вопрос
      description: Четко сформулируйте вопрос о процессах, документации или правилах организации
      placeholder: "Например: Как правильно создать ветку для новой функциональности? Или: Где найти информацию о процессе код-ревью?"
    validations:
      required: true

  - type: dropdown
    id: question_category
    attributes:
      label: Категория вопроса
      description: К какой области относится ваш вопрос?
      options:
        - Процессы разработки
        - Правила организации
        - Документация
        - Инструменты и настройки
        - Коммуникация и взаимодействие
        - Онбординг и адаптация
        - Код-ревью и мерж-реквесты
        - Другое (опишите в вопросе)
    validations:
      required: true

  - type: checkboxes
    id: checked_resources
    attributes:
      label: Что вы уже проверили?
      description: Отметьте ресурсы, которые вы уже изучили
      options:
        - label: "[Onboarding Guide](ONBOARDING.md)"
        - label: "[Руководство по вкладу](CONTRIBUTING.md)"
        - label: "[Кодекс поведения](CODE_OF_CONDUCT.md)"
        - label: Существующие Issues (поискал(а) похожие вопросы)
        - label: Чат организации (Telegram/Дискорд)
        - label: README.md интересующего проекта
        - label: Ничего не проверял(а) (это первый шаг)

  - type: textarea
    id: context
    attributes:
      label: Контекст вопроса
      description: Опишите ситуацию, в которой возник вопрос
      placeholder: |
        ### Если вопрос связан с конкретной ситуацией:
        1. Ситуация: Что вы пытаетесь сделать?
        2. Ожидание: Что, по вашему мнению, должно произойти?
        3. Реальность: Что происходит на самом деле?
        
        ### Если это общий вопрос о процессе:
        1. Какую часть процесса вы не понимаете?
        2. Что вызывает затруднения?
        3. Какой информации не хватает?
    validations:
      required: true

  - type: textarea
    id: related_sections
    attributes:
      label: Связанные разделы документации
      description: Если знаете, укажите конкретные разделы документов, которые относятся к вашему вопросу
      placeholder: |
        Например:
        - Onboarding Guide → раздел "Жизненный цикл задачи"
        - CONTRIBUTING.md → раздел "Система меток"
        - CODE_OF_CONDUCT.md → раздел "Процесс сообщения о нарушениях"
    validations:
      required: false

  - type: textarea
    id: assumptions
    attributes:
      label: Ваши предположения
      description: Какие у вас есть предположения или догадки по ответу на вопрос?
      placeholder: "Например: Предполагаю, что нужно создавать ветку от main, но не уверен в формате именования..."
    validations:
      required: false

  - type: dropdown
    id: audience
    attributes:
      label: Кому может быть полезен ответ?
      description: Кто еще может быть заинтересован в ответе на этот вопрос?
      multiple: true
      options:
        - Только мне (личный/специфический вопрос)
        - Всем новым участникам
        - Всем внутренним разработчикам
        - Всем контрибьюторам (включая внешних)
        - Конкретной роли (разработчики/ревьюверы/модераторы)
        - Всем участникам организации
    validations:
      required: true

  - type: checkboxes
    id: response_format
    attributes:
      label: Желаемый формат ответа
      description: Как вы хотели бы получить ответ?
      options:
        - label: "Письменный ответ в этом Issue (будет доступен всем)"
        - label: "Обновление документации (если вопрос выявил пробел)"
        - label: "Личное сообщение (если вопрос конфиденциальный)"
        - label: "Обсуждение на встрече команды (если требует коллективного решения)"
        - label: "Запись видео/скринкаста (если нужна визуализация)"

  - type: dropdown
    id: urgency
    attributes:
      label: Срочность вопроса
      description: Насколько срочно вам нужен ответ?
      options:
        - "🚨 Критическая срочность (блокирует работу прямо сейчас)"
        - "🔴 Высокая срочность (нужен в течение 24 часов)"
        - "🟡 Средняя срочность (нужен в течение 3 рабочих дней)"
        - "🟢 Низкая срочность (можно подождать неделю)"
        - "⚪ Общий вопрос (без конкретных сроков)"
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Дополнительная информация
      description: Любая другая информация, которая поможет лучше понять ваш вопрос
      placeholder: |
        - Ссылки на связанные Issues или PR
        - Скриншоты или примеры кода (если применимо)
        - Информация о вашей роли в организации
        - Особые обстоятельства или контекст
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Для команды NotDoneByOnly (секция не видна автору вопроса)
        
        *Эта секция видна только участникам организации для внутреннего использования*

  - type: dropdown
    id: team_category
    attributes:
      label: Категория вопроса (для команды)
      description: К какой категории относится вопрос для внутренней классификации?
      options:
        - Понимание процессов
        - Техническая реализация процесса
        - Документация и ясность
        - Коммуникация и взаимодействие
        - Инструменты и настройки
        - Правила и политики
        - Онбординг и адаптация

  - type: dropdown
    id: response_needed_from
    attributes:
      label: От кого нужен ответ?
      description: Кто должен ответить на этот вопрос?
      multiple: true
      options:
        - Основатели организации
        - Модераторы/администраторы
        - Специфическая роль (указать в комментарии)
        - Любой опытный участник
        - Требуется обсуждение в команде

  - type: checkboxes
    id: team_labels
    attributes:
      label: Метки для внутреннего использования
      description: Какие метки добавить к этому вопросу?
      options:
        - label: "priority: высокий (срочный вопрос)"
        - label: "priority: средний (важный, но не срочный)"
        - label: "priority: низкий (общий вопрос)"
        - label: "первая задача (можно использовать для FAQ)"
        - label: "нужна помощь (требует обсуждения)"
        - label: "требует обновления документации"
        - label: "частый вопрос (добавить в FAQ)"

  - type: markdown
    attributes:
      value: |
        ## Ожидания по ответу
        
        Обычные сроки ответа:
        - Срочные вопросы: в течение 24 часов
        - Обычные вопросы: в течение 3 рабочих дней
        - Общие вопросы: в течение 7 рабочих дней
        
        Ответ может быть предоставлен в виде:
        1. Прямого ответа в комментарии
        2. Ссылки на существующую документацию
        3. Обновления документации с последующей ссылкой
        4. Организации обсуждения/встречи
        
        Спасибо за ваш вопрос! Помогая вам, мы улучшаем наши процессы для всех.