name: Ошибка в документации или процессе
description: Сообщите об ошибке в документации, шаблонах или процессе организации NotDoneByOne
title: "[ОШИБКА]: "
labels: ["type: ошибка"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Ошибка в документации или процессах NDO
        
        Используйте эту форму для сообщения об:
        - Ошибках в документации (опечатки, неточности, противоречия)
        - Проблемах в шаблонах репозиториев, Issues, PR
        - Ошибках в процессах организации
        - Несоответствиях между документацией и реальными процессами

  - type: checkboxes
    id: error_location
    attributes:
      label: Где обнаружена ошибка?
      description: Выберите, где находится ошибка
      options:
        - label: "Onboarding Guide (ONBOARDING.md)"
        - label: "Руководство по вкладу (CONTRIBUTING.md)"
        - label: "Кодекс поведения (CODE_OF_CONDUCT.md)"
        - label: "Шаблоны репозиториев"
        - label: "Шаблоны Issues"
        - label: "Шаблоны Pull Request"
        - label: "Система меток"
        - label: "GitHub Actions/Workflows"
        - label: "README.md или другая документация проектов"
        - label: "Процессы организации (не документированные)"
        - label: "Другое (укажите ниже)"

  - type: textarea
    id: other_location
    attributes:
      label: Другое местоположение ошибки
      description: Если выбрали "Другое", укажите точный путь/название
      placeholder: "Например: repository-templates/default/.github/PULL_REQUEST_TEMPLATE.md или название процесса"
    validations:
      required: false

  - type: textarea
    id: current_state
    attributes:
      label: Текущее (ошибочное) состояние
      description: Подробно опишите, что происходит сейчас и почему это ошибка
      placeholder: |
        Примеры:
        - В документе указана неверная команда: `git commit -m "message"`
        - В шаблоне PR отсутствует обязательное поле
        - Процесс требует действий, которые технически невозможны
        - Два документа противоречат друг другу
    validations:
      required: true

  - type: textarea
    id: expected_state
    attributes:
      label: Ожидаемое (правильное) состояние
      description: Опишите, как должно быть правильно
      placeholder: |
        Примеры:
        - Должно быть: `git commit -m "feat: description"`
        - В шаблоне должно быть поле "Тип изменений"
        - Процесс должен учитывать технические ограничения
        - Документы должны быть согласованы
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Шаги для воспроизведения
      description: Пошагово опишите, как найти/увидеть ошибку
      placeholder: |
        1. Открыть документ: CONTRIBUTING.md
        2. Перейти к разделу: "Стиль кода и коммиты"
        3. Найти: Пример коммита на строке 45
        4. Увидеть ошибку: Неправильный формат сообщения коммита
    validations:
      required: true

  - type: input
    id: exact_location
    attributes:
      label: Точное местоположение
      description: Если возможно, укажите точную строку, раздел или ссылку
      placeholder: "Например: ONBOARDING.md#L45, или: раздел 'Жизненный цикл задачи', пункт 2.3"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Скриншоты или примеры
      description: Если возможно, опишите или прикрепите скриншоты/примеры ошибки
      placeholder: |
        Скриншот ошибки: [прикрепите файл]
        Пример ошибочного кода:
        ```markdown
        ## Неправильный заголовок
        ```
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Серьезность ошибки
      description: Насколько критична эта ошибка для работы организации?
      options:
        - "🟥 Критическая — блокирует работу организации или ведет к серьезным проблемам"
        - "🟧 Серьезная — вызывает путаницу, ошибки или неэффективность"
        - "🟨 Средняя — затрудняет понимание или использование"
        - "🟩 Незначительная — опечатка, мелкая неточность, косметическая проблема"
    validations:
      required: true

  - type: checkboxes
    id: affected_users
    attributes:
      label: Кто затронут ошибкой?
      description: Выберите все подходящие варианты
      options:
        - label: "Все участники организации"
        - label: "Новые участники (затрудняет онбординг)"
        - label: "Внешние контрибьюторы"
        - label: "Внутренние разработчики"
        - label: "Администраторы/модераторы"
        - label: "Конкретная роль/группа (опишите ниже)"
        - label: "Не уверен (нужно оценить)"

  - type: textarea
    id: affected_group_details
    attributes:
      label: Детали затронутой группы
      description: Если выбрали "Конкретная роль/группа", укажите какие именно
      placeholder: "Например: только ревьюверы, только разработчики на Python, и т.д."
    validations:
      required: false

  - type: textarea
    id: proposed_fix
    attributes:
      label: Предлагаемое исправление
      description: Если у вас есть идеи по исправлению, опишите их здесь
      render: markdown
      placeholder: |
        ### Для текстовых ошибок:
        **Было:**
        ```markdown
        git commit -m "message"
        ```
        
        **Стало:**
        ```markdown
        git commit -m "feat: add new feature"
        ```
        
        ### Для ошибок в процессе:
        1. Ошибочный шаг: Требуется подтверждение от 3 ревьюверов
        2. Исправление: Требовать подтверждение от 2 ревьюверов
        3. Связанные документы: Обновить CONTRIBUTING.md и шаблоны PR
        
        ### Для структурных ошибок:
        - Переместить раздел X перед разделом Y
        - Добавить подраздел с примерами
        - Удалить устаревшую информацию
    validations:
      required: false

  - type: checkboxes
    id: related_docs_check
    attributes:
      label: Какие документы нужно обновить?
      description: Какие документы могут потребовать обновления при исправлении ошибки?
      options:
        - label: "Только указанный документ"
        - label: "Onboarding Guide (ONBOARDING.md)"
        - label: "Руководство по вкладу (CONTRIBUTING.md)"
        - label: "Кодекс поведения (CODE_OF_CONDUCT.md)"
        - label: "Шаблоны репозиториев"
        - label: "Шаблоны Issues/PR"
        - label: "Несколько документов (укажите ниже)"
        - label: "Не уверен, нужно проверить"

  - type: textarea
    id: related_docs_details
    attributes:
      label: Детали связанных документов
      description: Если нужно обновить несколько документов или есть специфические требования
      placeholder: |
        Нужно обновить:
        1. CONTRIBUTING.md - раздел о коммитах
        2. Шаблон PR - поле формата коммитов
        3. Onboarding Guide - примеры коммитов
    validations:
      required: false

  - type: textarea
    id: history
    attributes:
      label: История возникновения ошибки
      description: Если известно, предоставьте информацию о возникновении ошибки
      placeholder: |
        - Когда все работало правильно: Версия документации от января 2025
        - Когда замечена ошибка: 15 марта 2025
        - Возможная причина: Обновление процесса без обновления документации
        - Связанные изменения: PR #123, который изменил процесс
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Контекст/окружение
      description: В каком контексте была обнаружена ошибка?
      options:
        - "Во время онбординга нового участника"
        - "При работе над проектом"
        - "При создании PR/Issue"
        - "При настройке репозитория"
        - "Во время код-ревью"
        - "При обучении/объяснении процесса"
        - "Случайно обнаружил(а)"
        - "Другое (опишите в дополнительной информации)"
    validations:
      required: false

  - type: checkboxes
    id: team_priority
    attributes:
      label: Приоритет исправления (для команды)
      description: Какой приоритет имеет исправление этой ошибки?
      options:
        - label: "priority: высокий (критическая ошибка, блокирует работу)"
        - label: "priority: средний (серьезная ошибка, нужно исправить в ближайшее время)"
        - label: "priority: низкий (незначительная ошибка, можно исправить при возможности)"

  - type: checkboxes
    id: special_labels
    attributes:
      label: Специальные метки
      description: Добавить специальные метки для этой ошибки
      options:
        - label: "критический баг (если ошибка критически важна для работы организации)"
        - label: "первая задача (если ошибка простая и подходит для новых контрибьюторов)"
        - label: "нужна помощь (если требуется обсуждение или помощь в исправлении)"
        - label: "процесс (если ошибка в процессе, а не в документации)"

  - type: textarea
    id: workaround
    attributes:
      label: Временное решение (workaround)
      description: Если есть временное решение проблемы, опишите его здесь
      placeholder: |
        Пока ошибка не исправлена, можно:
        - Использовать команду X вместо Y
        - Игнорировать раздел Z
        - Следовать альтернативному процессу из документа A
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Процесс исправления
        
        После создания Issue:
        1. Ошибка будет классифицирована и назначен приоритет
        2. Будет назначен ответственный за исправление
        3. Исправление будет внесено в соответствующие документы/процессы
        4. Все связанные документы будут проверены на согласованность
        5. Вас уведомят о результате исправления
        
        Ожидаемые сроки:
        - Критические ошибки: исправление в течение 24-48 часов
        - Серьезные ошибки: исправление в течение 3-5 рабочих дней
        - Незначительные ошибки: исправление при возможности
        
        Спасибо за помощь в улучшении качества документации и процессов NDO!